---
- name: Install apache2 and upload my web page
  hosts: all
  become: yes

  vars:
    source_file: ./index.html
    destin_file: /var/www/html


  tasks:
  - name: install Apache web server
    apt: name=apache2 state=present


  - name: Copy MyHomePage to servers
    copy: src={{ source_file }} dest={{ destin_file }} mode=0555
    notify: Restart Apache

  - name: Start and enable web server
    service: name=apache2 state=started enabled=yes



  handlers:
  - name: Restart Apache
    service: name=apache2 state=restarted