---
- name: Install apache2 web-server
  hosts: all
  become: yes

  tasks:
  - name: Install apache2 web-server
    apt:  name=apache2 state=present


  - name: Apache2 enable and start
    service: name=apache2 state=started enabled=yes