---
- name: Configure and Install PostgreSQL and Patroni
  hosts: nodes
  become: yes


  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install net-tools
      ansible.builtin.apt:
        name: net-tools
        state: present

    - name: Install PostgreSQL and development files
      ansible.builtin.apt:
        name:
          - postgresql-14
          - postgresql-contrib
        state: present

    - name: Stop PostgreSQL service
      ansible.builtin.systemd:
        name: postgresql
        state: stopped

    - name: Create symlinks for PostgreSQL binaries
      ansible.builtin.shell: sudo ln -s /usr/lib/postgresql/14/bin/* /usr/sbin/

    - name: Install Python and required packages
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
          - python3-dev
          - python3-testresources
        state: present

    - name: Install setuptools 
      ansible.builtin.pip:
        name: setuptools 
        extra_args: --upgrade

    - name: Install psycopg2, patroni, and python-etcd using pip
      ansible.builtin.pip:
        name:
          - psycopg2-binary
          - patroni
          - python-etcd
