---
- name: Install Zabbix agent2
  hosts: all
  become: yes

  vars:
    source_file: ./zabbix_agent2.conf
    destin_file: /etc/zabbix

  tasks:
  - shell: awk -F= '/^VERSION_ID=/{print $2}' /etc/os-release | sed 's/\"//g'
    register: version

  - shell: awk -F= '/^ID=/{print $2}' /etc/os-release | sed 's/\"//g'
    register: distrib

  - debug:
      msg: "https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+{{ distrib.stdout }}{{ version.stdout }}_all.deb"



  - block:

      - name: Wget zabbix agent2 package
        ansible.builtin.get_url:
          url: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+{{distrib.stdout}}{{version.stdout}}_all.deb
          dest: /home/user


      - name: Depackage zabbix
        ansible.builtin.shell: dpkg -i /home/user/zabbix-release_6.4-1+{{distrib.stdout}}{{version.stdout}}_all.deb
        notify: Apt update Debian

    when: ansible_os_family == "Debian"



  handlers:
  - name: Apt update Debian
    ansible.builtin.apt:
      update_cache: yes



