- name: centOS_template_rvn
  hosts: test # список хостов
  become: True
  tasks:
    - name: Change hostname
      ansible.builtin.hostname:
        name: name

    - name: Hot disk resize
      ansible.builtin.command: "echo 1 > /sys/class/block/sda/device/rescan"

    - name: Extend an existing partition to fill all available space
      community.general.parted:
        device: /dev/sda
        number: 2
        part_end: "100%"
        resize: true
        state: present

    - name: Resize the volume group /dev/sda2 to the maximum possible
      community.general.lvg:
        vg: vg0
        pvs: /dev/sda2
        pvresize: true

    - name: Extend the logical volume to consume all remaining space in the volume group
      community.general.lvol:
        vg: vg0
        lv: /dev/vg0/root  
        size: +100%FREE

    - name: 'Extend the FS'
      filesystem:
        fstype: xfs
        dev: /dev/vg0/root
        resizefs: yes

    - name: copy keys to hosts
      copy:
        src: /etc/ansible/playbooks/keys
        dest: /home/user/.ssh/authorized_keys
        follow: yes #no = не перезаписывает файл

